/**
 * SONIQ Frequency Mode — Chant Catalog
 *
 * The cinematic / sacred chant style table for Frequency Mode. Each entry pairs
 * a tradition + vibe with a loopable mantra seed and a Suno-ready style prompt.
 *
 * Server-side only — never expose this file to the client. The `sunoPrompt`
 * field IS the IP: it is the production-grade Suno style string that turns a
 * chant pick into a rendered chant layer. Only the resolved, composed prompt
 * ever leaves the server (via POST /api/frequency), and the per-chant
 * `sunoPrompt` is NEVER returned on the GET list. Mirror the api/_loop_anchor.js
 * convention: client gets the client-safe projection, the transform stays here.
 *
 * Item shape:
 *   { id, name, tradition, emoji, color (hex), vibe,
 *     pairsWith: [freqIds or intent words],
 *     clientDesc (no medical claims),
 *     chantSeed (actual loopable mantra text),
 *     sunoPrompt (SERVER-ONLY IP — never sent to client) }
 *
 * SAFETY: clientDesc carries NO medical claims. Keep it experiential/sensory.
 */

const CHANTS = [
  { id: "tibetan-overtone", name: "Tibetan Overtone Chant", tradition: "Tibetan Buddhist (Gyuto / Gyume monastic)", emoji: "🕎", color: "#C4622D", vibe: "A single monk's voice splitting into a ceiling of harmonics over a subterranean drone.", pairsWith: ["healing", "intuition", "grounding", "solfeggio-528", "solfeggio-963", "binaural-theta-6", "tone-136"], clientDesc: "Deep multiphonic monastery voices that bloom into shimmering overtones above an endless drone.", chantSeed: "Om Mani Padme Hum", sunoPrompt: "[Tibetan overtone throat chant, deep multiphonic drone, monastery stone reverb, very slow, long breaths between phrases]" },
  { id: "gregorian-plainchant", name: "Gregorian Plainchant", tradition: "Western Christian (Latin liturgical)", emoji: "⛪", color: "#B89A6A", vibe: "Unison male voices drifting through candlelit stone like smoke through a cathedral.", pairsWith: ["focus", "stillness", "reverence", "tone-432", "solfeggio-528", "binaural-alpha-10"], clientDesc: "Floating unison Latin melodies that move in slow, weightless waves through vast stone halls.", chantSeed: "Kyrie eleison, Christe eleison, Kyrie eleison", sunoPrompt: "[Gregorian plainchant, unison male voices, candlelit cathedral reverb, free-flowing modal melody, no rhythm]" },
  { id: "om-aum-drone", name: "OM / Aum Drone", tradition: "Yogic / Pan-Indic", emoji: "🕉️", color: "#E0A93B", vibe: "One eternal syllable rising and dissolving, the sound the universe hums to itself.", pairsWith: ["meditation", "grounding", "stillness", "solfeggio-528", "tone-136", "binaural-theta-6", "schumann-783"], clientDesc: "The single sustained OM syllable swelling and fading in slow ocean-like breaths.", chantSeed: "Aum... Aum... Aum...", sunoPrompt: "[Sustained group OM drone, deep collective hum, tanpura undertone, endless swell and decay, no words]" },
  { id: "gayatri-mantra", name: "Gayatri Mantra", tradition: "Vedic Sanskrit", emoji: "🌅", color: "#D98A45", vibe: "A sunrise prayer in ancient Sanskrit, warm and unbroken as first light.", pairsWith: ["healing", "clarity", "intuition", "solfeggio-528", "solfeggio-639", "tone-432", "binaural-alpha-10"], clientDesc: "The dawn-prayer Sanskrit mantra sung in warm, flowing devotional lines over a tanpura.", chantSeed: "Om Bhur Bhuvah Svah, Tat Savitur Varenyam", sunoPrompt: "[Vedic Sanskrit Gayatri mantra, warm devotional male voice, tanpura drone, sunrise raga, slow and reverent]" },
  { id: "so-ham-breath", name: "So Ham Breath Mantra", tradition: "Yogic / Advaita", emoji: "🌬️", color: "#7FA8B0", vibe: "Inhale 'so', exhale 'ham' — a whispered mantra that breathes you back to the body.", pairsWith: ["sleep", "stillness", "calm", "binaural-theta-6", "binaural-delta-2", "solfeggio-528", "schumann-783"], clientDesc: "A soft breath-synced 'So Ham' whisper that rises and falls with the rhythm of slow breathing.", chantSeed: "So... Ham... So... Ham...", sunoPrompt: "[Breath-synced So Ham whisper mantra, intimate close voice, airy exhale, slow tidal breathing pace, near-silence]" },
  { id: "kirtan-call-response", name: "Kirtan Call & Response", tradition: "Bhakti / Hindu devotional", emoji: "🪔", color: "#E36B8A", vibe: "A leader calls, the room answers — the same names sung until the walls glow.", pairsWith: ["heart", "joy", "devotion", "solfeggio-639", "solfeggio-528", "tone-432", "binaural-alpha-10"], clientDesc: "Warm call-and-response devotional singing that builds gently from one voice into a whole circle.", chantSeed: "Hare Krishna Hare Krishna, Krishna Krishna Hare Hare", sunoPrompt: "[Bhakti kirtan call and response, lead voice answered by warm group, harmonium and hand drum, gently rising, communal]" },
  { id: "sufi-zikr", name: "Sufi Zikr", tradition: "Sufi / Islamic mysticism", emoji: "🌙", color: "#5B7FB4", vibe: "A breathing circle pulsing one Name, turning until the self spins away.", pairsWith: ["heart", "surrender", "trance", "solfeggio-639", "solfeggio-741", "binaural-theta-6", "tone-432"], clientDesc: "A hypnotic breath-driven repetition of the divine Name that pulses and circles like a slow turning dance.", chantSeed: "Allah Hu... Allah Hu... Hu... Hu...", sunoPrompt: "[Sufi zikr trance chant, breath-pulsed repetition of one name, ney flute, circling rhythm, ecstatic but slow]" },
  { id: "byzantine-ison", name: "Byzantine Ison Chant", tradition: "Eastern Orthodox", emoji: "☦", color: "#9C7B3A", vibe: "A melody walks across a held drone like a candle carried through a golden vault.", pairsWith: ["reverence", "stillness", "focus", "tone-432", "solfeggio-528", "solfeggio-963", "binaural-alpha-10"], clientDesc: "An ornamented chant line moving over a continuous held drone, gilded with deep gold-domed reverb.", chantSeed: "Agios o Theos, Agios Ischyros, Agios Athanatos", sunoPrompt: "[Byzantine Orthodox chant, ornamented melody over held ison drone, gold-domed reverb, microtonal, solemn male voices]" },
  { id: "native-vocable", name: "Native Vocable Round", tradition: "Indigenous North American (round-dance style)", emoji: "🪶", color: "#A85C3E", vibe: "Wordless syllables riding an open-sky melody, breath of plains and pine smoke.", pairsWith: ["grounding", "healing", "nature", "schumann-783", "solfeggio-528", "tone-432", "binaural-theta-6"], clientDesc: "Open-throated wordless vocables carried on a soaring high-plains melody beneath a wide sky.", chantSeed: "Wey-ya hey-ya, hey-ya ho, wey-ya hey-ya ho", sunoPrompt: "[Indigenous vocable round-dance chant, open-throat soaring vocables, wide outdoor air, distant heartbeat, high-plains melody]" },
  { id: "shamanic-drone", name: "Shamanic Throat Drone", tradition: "Siberian / Mongolian shamanic (khoomei lineage)", emoji: "🦅", color: "#6E5A8A", vibe: "A low growl threaded with a whistling overtone, the voice of wind over frozen steppe.", pairsWith: ["intuition", "journey", "trance", "binaural-theta-6", "binaural-delta-2", "solfeggio-852", "tone-136"], clientDesc: "A raw low throat drone laced with a thin whistling overtone, evoking wind across the open steppe.", chantSeed: "Hoooo... eeee... hoooo... (low throat drone)", sunoPrompt: "[Mongolian shamanic throat drone, low growl with whistling overtone, frame-drum pulse, cold open-steppe wind, hypnotic]" },
  { id: "angelic-feminine-choir", name: "Angelic Sacred-Feminine Choir", tradition: "New-age sacred-feminine devotional", emoji: "👼", color: "#E4B7D8", vibe: "Layered women's voices rising in soft 'ah's like light spilling through high windows.", pairsWith: ["heart", "healing", "tenderness", "solfeggio-528", "solfeggio-639", "tone-432", "binaural-alpha-10"], clientDesc: "Soft layered women's voices rising in wordless 'ah' harmonies like light through high windows.", chantSeed: "Aaah... aaah... ooh... aaah...", sunoPrompt: "[Layered angelic female choir, wordless soft ahs, airy soprano harmonies, halo reverb, weightless and luminous]" },
  { id: "gospel-hum", name: "Gospel Hum", tradition: "African-American spiritual / gospel", emoji: "🕊️", color: "#C98A55", vibe: "Closed-mouth voices swaying in warm harmony, comfort with the lights low.", pairsWith: ["heart", "comfort", "calm", "solfeggio-528", "solfeggio-639", "tone-432", "binaural-alpha-10"], clientDesc: "Warm closed-mouth gospel humming swaying in soulful harmony like an empty church at dusk.", chantSeed: "Mmm... mmm-hmm... mmm...", sunoPrompt: "[Gospel closed-mouth hum, warm soulful harmony, slow swaying sway, empty church ambience, tender and low]" },
  { id: "cinematic-choir", name: "Modern Cinematic Choir", tradition: "Contemporary film-score choral", emoji: "🎬", color: "#8FA3C4", vibe: "A vast mixed choir holding one wide vowel, an epic horizon with nothing to fear.", pairsWith: ["focus", "clarity", "uplift", "binaural-gamma-40", "binaural-alpha-10", "solfeggio-528", "tone-432"], clientDesc: "A wide modern film-score choir holding sustained open vowels in clean, cinematic stereo space.", chantSeed: "Aah... oh... aah... (sustained open vowels)", sunoPrompt: "[Modern cinematic choir, wide mixed voices on sustained open vowels, clean epic stereo, slow swells, no lyrics]" },
  { id: "heart-sutra-mantra", name: "Heart Sutra Mantra", tradition: "Mahayana Buddhist (Prajnaparamita)", emoji: "🪷", color: "#5FA08C", vibe: "A gentle going-beyond mantra, each phrase a step over the far shore of thought.", pairsWith: ["clarity", "letting-go", "meditation", "solfeggio-741", "solfeggio-852", "binaural-theta-6", "tone-136"], clientDesc: "The serene 'gone beyond' mantra chanted in calm, rolling phrases over a soft bell undertone.", chantSeed: "Gate Gate Paragate Parasamgate Bodhi Svaha", sunoPrompt: "[Heart Sutra mantra chant, calm rolling Sanskrit phrases, soft singing bowl undertone, temple air, serene and unhurried]" }
];

module.exports = { CHANTS };
